### ISSUE TITLE
When step value less than 0.5 , widget is often problematic

### ISSUE THREAD

**Issue by ChengMaoDSM** [mendixlabs/slider#13] opened 2018-09-13 04:55 UTC
I have a problem in the widget of Mendix, Can you Help me, please.
When I set the step value less than 0.5.  Warning " Step value is invalid: max-min(5 - -5  ) , should be evenly divisible by the step value 0.1".

example :
1. ‘Min -5,Max 5 Step 0.5 ‘ is OK, 
2. ‘Min -5,Max 5 Step 0.1 ‘ is Warning ,
3. 'Min -0.2,Max 0.2 Step 0.01 ‘ is Warning .

I think second and third example should work because
(5 - (-5))/0.1 = 10/0.1 = 100, and is an divisible, and
(0.2 - (-0.2))/0.01 = 0.4/0.01 = 40, and is divisible.

**Comment by McDoyen** [comment] 2018-09-13 10:46
Hi @ChengMaoDSM,

Thanks for reporting this issue.
We will look into it and get back to you as soon as possible.

Cheers,
Paul.

**Comment by Andries-Smit** [comment] 2018-10-02 13:27
Dear Cheng,

The issue is resolved in version 1.2.1 and is available in the app store. https://appstore.home.mendix.com/link/app/48786/

With kind regards, Andries

**Closed as completed by Andries-Smit** 2018-10-02 13:27 UTC
